name: AoC 2025

on:
  pull_request:
    paths:
      - 'aoc-2025/**'

jobs:
  aoc-2025:
    name: AoC 2025
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aoc-2025
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.24"
      - name: Install dependencies
        run: go mod tidy
      - name: Run linter
        run: go fmt ./... && go vet ./...
      - name: Run tests
        run: go test -v ./...
      - name: Build
        run: go build
